# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rails_metrics}
  s.version = "0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jos\303\251 Valim"]
  s.date = %q{2010-02-15}
  s.description = %q{Metrics measurement for your app on top of ActiveSupport::Notifications}
  s.email = %q{contact@engineyard.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG.rdoc",
     "Gemfile",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO.rdoc",
     "app/controllers/rails_metrics_controller.rb",
     "app/helpers/rails_metrics_helper.rb",
     "app/views/layouts/rails_metrics.html.erb",
     "app/views/rails_metrics/_request.html.erb",
     "app/views/rails_metrics/_row.html.erb",
     "app/views/rails_metrics/all.html.erb",
     "app/views/rails_metrics/chart.html.erb",
     "app/views/rails_metrics/index.html.erb",
     "app/views/rails_metrics/show.html.erb",
     "config/routes.rb",
     "lib/generators/rails_metrics_generator.rb",
     "lib/rails_metrics.rb",
     "lib/rails_metrics/async_consumer.rb",
     "lib/rails_metrics/engine.rb",
     "lib/rails_metrics/middleware.rb",
     "lib/rails_metrics/orm/active_record.rb",
     "lib/rails_metrics/orm/data_mapper.rb",
     "lib/rails_metrics/payload_parser.rb",
     "lib/rails_metrics/store.rb",
     "lib/rails_metrics/version.rb",
     "public/images/rails_metrics/arrow_down.png",
     "public/images/rails_metrics/arrow_up.png",
     "public/images/rails_metrics/cancel.png",
     "public/images/rails_metrics/chart_pie.png",
     "public/images/rails_metrics/page_white_delete.png",
     "public/images/rails_metrics/page_white_go.png",
     "public/images/rails_metrics/tick.png",
     "public/javascripts/rails_metrics/g.pie-min.js",
     "public/javascripts/rails_metrics/g.raphael-min.js",
     "public/javascripts/rails_metrics/raphael-min.js",
     "public/stylesheets/rails_metrics.css"
  ]
  s.homepage = %q{http://github.com/engineyard}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Metrics measurement for your app on top of ActiveSupport::Notifications}
  s.test_files = [
    "test/dummy/app/controllers/application_controller.rb",
     "test/dummy/app/controllers/users_controller.rb",
     "test/dummy/app/helpers/application_helper.rb",
     "test/dummy/app/models/metric.rb",
     "test/dummy/app/models/notification.rb",
     "test/dummy/app/models/user.rb",
     "test/dummy/config/application.rb",
     "test/dummy/config/boot.rb",
     "test/dummy/config/environment.rb",
     "test/dummy/config/environments/development.rb",
     "test/dummy/config/environments/production.rb",
     "test/dummy/config/environments/test.rb",
     "test/dummy/config/initializers/backtrace_silencers.rb",
     "test/dummy/config/initializers/cookie_verification_secret.rb",
     "test/dummy/config/initializers/session_store.rb",
     "test/dummy/config/routes.rb",
     "test/dummy/db/migrate/20100106152343_create_metrics.rb",
     "test/dummy/db/migrate/20100108120821_create_users.rb",
     "test/integration/instrumentation_test.rb",
     "test/integration/navigation_test.rb",
     "test/orm/active_record_test.rb",
     "test/payload_parser_test.rb",
     "test/rails_metrics_test.rb",
     "test/store_test.rb",
     "test/support/helpers.rb",
     "test/support/instrumentation.rb",
     "test/support/mock_store.rb",
     "test/support/webrat/integrations/rails.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

